### ISSUE TITLE
a2dp-app-osmc: pairing is successful but connection fails

### ISSUE THREAD

**Issue by ianks** [osmc/osmc#305]
In a fresh install of osmc (with updates), I am correctly able to pair a device, but connecting causes an immediate disconnect. 

Here is how I am connecting to the device:

```
[bluetooth]# connect 00:00:00:00:8D:41 
Attempting to connect to 00:00:00:00:8D:41
[CHG] Device 00:00:00:00:8D:41 Connected: yes
Connection successful   
Agent unregistered      
[DEL] Controller 5C:F3:70:76:BB:19 osmc [default]
```

When the connection fails, the systemd bluetooth service fails, signalling a SEGV signal as the failure reason.

```
* bluetooth.service - Bluetooth service
   Loaded: loaded (/lib/systemd/system/bluetooth.service; enabled)
  Drop-In: /etc/systemd/system/bluetooth.service.d
           `-local.conf
   Active: failed (Result: signal) since Tue 2016-04-19 00:45:01 EDT; 3min 59s ago
     Docs: man:bluetoothd(8)
  Process: 257 ExecStart=/usr/libexec/bluetooth/bluetoothd (code=killed, signal=SEGV)
 Main PID: 257 (code=killed, signal=SEGV)
   Status: "Running"

Apr 19 00:41:57 osmc bluetoothd[257]: Bluetooth daemon 5.38
Apr 19 00:41:57 osmc bluetoothd[257]: Starting SDP server
Apr 19 00:41:57 osmc bluetoothd[257]: Bluetooth management interface 1.10 initialized
Apr 19 00:41:57 osmc bluetoothd[257]: Failed to obtain handles for "Service Changed" characteristic
Apr 19 00:41:58 osmc bluetoothd[257]: Endpoint registered: sender=:1.7 path=/MediaEndpoint/A2DPSource
Apr 19 00:41:58 osmc bluetoothd[257]: Endpoint registered: sender=:1.7 path=/MediaEndpoint/A2DPSink
Apr 19 00:45:01 osmc bluetoothd[257]: /org/bluez/hci0/dev_00_00_00_00_8D_41/fd0: fd(20) ready
Apr 19 00:45:01 osmc systemd[1]: bluetooth.service: main process exited, code=killed, status=11/SEGV
Apr 19 00:45:01 osmc systemd[1]: Unit bluetooth.service entered failed state.
```

There also seems to be some peculiarities with the pulseaudio bluetooth module. 

```
Apr 19 00:41:58 osmc pulseaudio[247]: E: [pulseaudio] bluez4-util.c: org.bluez.Manager.GetProperties() failed: org.freedesktop.DBus.Error.UnknownMethod: Method "GetProperties
" with signature "" on interface "org.bluez.Manager" doesn't exist
```

### Bluez logs in journalctl

```
osmc@osmc:~$ sudo journalctl | grep bluez                                                                                                                                    
Apr 19 00:41:58 osmc connmand[260]: Method "ListAdapters" with signature "" on interface "org.bluez.Manager" doesn't exist
Apr 19 00:41:58 osmc pulseaudio[247]: E: [pulseaudio] bluez4-util.c: org.bluez.Manager.GetProperties() failed: org.freedesktop.DBus.Error.UnknownMethod: Method "GetProperties" with signature "" on interface "org.bluez.Manager" doesn't exist
Apr 19 00:45:01 osmc bluetoothd[257]: /org/bluez/hci0/dev_00_00_00_00_8D_41/fd0: fd(20) ready
```

### Specs

1. Kernel: `Linux osmc 4.4.6-3-osmc #1 SMP PREEMPT Fri Apr 1 20:55:03 UTC 2016 armv7l GNU/Linux`
2. USB bluetooth dongle: `Bus 001 Device 004: ID 0a5c:21e8 Broadcom Corp. BCM20702A0 Bluetooth 4.0`

### Other

This bug is a regression with my setup, since I had bluetooth working a couple of weeks ago (prior to the April release). Please let me know how I can help to debug this further! :smile:

**Comment by samnazarko** [comment]
It's fixed in the latest bluez which will be available in the next update

**Comment by gezb** [comment]
Hi 

When you connect to your phone using connmanctl you also need to `trust` the device this maybe why you are seeing disconnections

**Comment by ianks** [comment]
@samnazarko Thank you kindly! Do you have a link for tracking this bug?

**Comment by ianks** [comment]
@samnazarko I have downloaded the new version and still experience this issue. I have no issues with this exact same setup on Arch Linux, fwiw.

**Comment by samnazarko** [comment]
Did you install the A2DP package after reinstalling?
