### ISSUE TITLE
Raspberry Pi 3 stuck on formating device

### ISSUE THREAD

**Issue by f0o** [osmc/osmc#346]
__Details__:
* Hardware:
* * Raspberry Pi 3
* * Class 10 microSDHC with 8G (genuine Samsung)
* * HDMI Connected screen
* * 2.5 Amps USB PSU
* * Laptop running Gentoo (4.4.6 kernel) and a USB-SD dongle
* Reproducible: Always
* Steps:
* * Download official OSMC_TGT_rbp2_20161224.img
* * `dd if=OSMC_TGT_rbp2_20161224.img of=/dev/sdc`
* * Insert SD into RPI3
* * Insert USB jack into RPI3
* * Screen now reads `Formating device`
* * No activity on the LEDs, No change after 12h of runtime
* * Unplug USB
* * Insert SD into Laptop again, See newly created EXT4.
* * Mount EXT4 - Empty.

__Attempt 2__:
* Manually extract filesystem.tar.xz onto said mounted EXT4
* Attempt to Boot
* Same behavior, Stuck again.

__Attempt 3__:
* Manually extract filesystem.tar.xz onto said mounted EXT4
* Remove filesystem.tar.xz from primary FAT32
* Attempt to Boot
* Blank screen

As this has been reported multiple times on the forums, this should be considered an actual bug.

I've tried to extract the zImage to see what the setup script is actually attempting to do but I had no luck in doing so.

From a naive interpretation of what I experience I would guess that it's a timing issue where the SD card is not formatted quickly enough and thus the next steps are being soft-failed and skipped rather than waited for.

Happy to serve as a lab-bunny for debugging. I'm on IRC under the same nick.

PS:
I cant find where `logger` writes logs to, any clues?
The code looks fine, couldn't find any obvious issues that would explain my behavior.

**Comment by samnazarko** [comment]
>As this has been reported multiple times on the forums, this should be considered an actual bug.

Do you have a link to some examples? I am not aware of any recent issues with the installer.

The first thing I would do is try with another SD card before you invest time in to debugging the installer. There should be an installer.log on the fat32 partition after the installation has run, but if the installer is not completing this may not be written out.

**Comment by samnazarko** [comment]
If you are happy to debug the installer and have a fairly recent APT based distro (Debian or Ubuntu), you could build the installer with netcat support.

*clone OSMC
* cd installer/target
* edit patches/rbp2-....patch
* change root= line to add debugip=IP-of-your-desktop
* run make
* dd the buildroot/output/images to SD
* connect Ethernet to Pi, and run netcat -lvp 9999 on your PC/laptop
* run /usr/bin/qt_target_installer -qws and you should be able to see the installer output over the network

**Comment by f0o** [comment]
Hi @samnazarko,

I'll make a debug patch tomorrow morning and give it a shot. Thanks for the pointers! :+1: 

as for the links:
https://discourse.osmc.tv/t/osmc-installation-stuck-formatting/2728
https://discourse.osmc.tv/t/usb-install-stuck-on-formatting-device/8667
https://discourse.osmc.tv/t/stuck-at-formatting-device/17139
https://discourse.osmc.tv/t/formatting-freezing-on-install-raspberry-pi-2/6148

The SD-card works fine, it's now running LibreELEC and before that it has been running OpenELEC without issues. However I dislike *ELEC because they dont give me enough `OS` and I really cant be arsed to have a crosscompile toolchain on my laptop ;)

**Comment by samnazarko** [comment]
Hi

>https://discourse.osmc.tv/t/osmc-installation-stuck-formatting/2728

The first thread was an OSMC bug that was fixed.
With the second thread we later found from the user that the USB stick had some issues.
With the third thread we found the user had a counterfeit Kingston card.
With the fourth, and final thread, we did not find an issue but did try and contact the user for further clarification.

I do acknowledge that there may be an issue with particular cards and our installer. I greatly appreciate that someone that is willing to test this, as some of our users are not always able to test and feedback.

The OSMC installer is based on 3.18 kernel, where as OSMC itself is based on 4.4 at the time of writing. When 4.10 lands, I will bump both installer and kernel to this version as this will be an LTS version. The installer uses the old mmc driver, but OSMC proper uses the SDHost driver. There is potentially a small set of SD cards which are compatible with one but not the other, and this is not ideal.

**Comment by f0o** [comment]
Is there a documentation on how to build the entire suite?

Just cd'ing into the installer/target and run `make rbp2` leaves me with a .img.gz that only contains the filesystem.tar.xz and nothing else. Make exits with no error-code (exit 0).

I've now gone into filesystem and make that as well as toolchain. Still no luck on the installer..

**Comment by samnazarko** [comment]
Hi

Running ```make rbp2``` should build everything for you, but as you have noted, our installer uses kpartx (which requires access to /dev/mapper). I have always found it problematic getting that to work under LXC and use KVM for builds.

The actual setup for DHCP is here: https://github.com/osmc/osmc/blob/master/installer/target/qt_target/qt_target_installer/init#L59.

You could adjust /etc/network/interfaces, and /sbin/ifup eth0. Hopefully this is enough to get you booting. 

There is also UART support (TX & RX) if you put 'uart' in the commandline.

Also, I realise that debugip= should be in cmdline.txt. You can either edit build.sh, or change it manually after building. For Raspberry Pi, you do not need to edit the kernel config patch. The last time I was debugging was on a different device. Try that first and it should just work.

**Comment by f0o** [comment]
Closing issue, mmc driver in 3.x didnt recognize the SDcard correctly.

**Comment by samnazarko** [comment]
I'll keep it open until I bump the installer kernel.

**Comment by mriscoc** [comment]
Same issue with a Patriot LX Series 8GB SDHC Class 10

**Comment by samnazarko** [comment]
It's taken a while, but this should now be fixed with the 2018.03 images or later, as we now use a more modern kernel, and in turn, the SDHost driver for MMC.
