### ISSUE TITLE
No hifiberry amp anymore - release 2020.11-1

### ISSUE THREAD

**Issue by denics** [osmc/osmc#579]
dear all,
I have just installed the 2020.11-1 upgrade on my RPi 3(waiting for RPi 4 :) ) and I have noted that we cannot choose hifiberry amp anymore from my osmc add-on

**Comment by samnazarko** [comment]
There was an issue preventing some overlays from working. This is now fixed. Just check for updates again

On 26 Nov 2020, at 16:51, Denix <notifications@github.com> wrote:

﻿

dear all,
I have just installed the 2020.11-1 upgrade on my RPi 3(waiting for RPi 4 :) ) and I have noted that we cannot choose hifiberry amp anymore from my osmc add-on

**Comment by denics** [comment]
then we can close. Thanks

**Comment by samnazarko** [comment]
It’s working?

On 26 Nov 2020, at 16:58, Denix <notifications@github.com> wrote:

﻿

then we can close. Thanks

**Comment by denics** [comment]
It is still not working from the "my osmc" interface, I can select only a limited number of items. However it is correctly loaded when manually added. 
Thanks

**Comment by samnazarko** [comment]
If it works via config.txt, then the support is there.
Unfortunately I don't have HifiBerry hardware for any modern version of Pi to test on, so I can't help here.
